title: ZhouYang Luo's Website
name: ZhouYang Luo
email: stupidme.me.lzy@gmail.com
description: Welcome to my website. I will share my ideas with you in here.

parallax_image_one: assets/images/background3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/laptop.png


project_one: Gemini
project_one_description: A blog website using Angular and beego.
project_one_url: https://github.com/luozhouyang/gemini
project_one_icon: star


project_two: SHU Campus
project_two_description: A tool aplication running Android OS. It's still storaged in my old github account for now.
project_two_url: https://github.com/StupidL/SHUCampus
project_two_icon: school

project_three: Embedded Tool
project_three_description: An android application for emdedded developer. It's still storaged in my old github account for now.
project_three_url: https://github.com/StupidL/EmbeddedTool
project_three_icon: android


project_four: TabPagerLayout
project_four_description: An android custom view based on ViewPager and TabLayout. It's still storaged in my old github account for now.  
project_four_url: https://github.com/StupidL/TabPagerLayout
project_four_icon: android


project_button: Github

github: https://github.com/luozhouyang
medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: http://localhost:4000/ #the url of your site

google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

